### PR TITLE
Add ability to test against custom function

### PR DESCRIPTION
**Pull request by drwharris**

### CODE REVIEW

**Comment by drwharris** [comment]
@crookedneighbor Are you happy with this?

**Comment by crookedneighbor** [comment]
@drwharris can you explain the rationale for passing the config as a second argument for the matching function?

**Comment by crookedneighbor** [comment]
Never mind, I see it now.

**Comment by crookedneighbor** [comment]
Merged in with https://github.com/crookedneighbor/markdown-it-link-attributes/commit/d08dbccf6d894d836b00fd22f0068e29c645fbf8

**Pull request closed without merging**
