### PR TITLE
Fix no-unused-expressions error in test/index.js

### PR DESCRIPTION
**Pull request by shirohana**

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I don't see how this was failing before. The master build looks fine. Is it possible that you're using a different version of standard than the one the repo is using?

**Comment by shirohana** [comment]
It looks strange... I changed my nvm version, cleanup node_modules, clone a clean copy from GitHub repo, the errors still shown up :(



How master branch test passed before?

**Comment by crookedneighbor** [comment]
What version of node are you using?

**Comment by shirohana** [comment]
Tried v8.1.2 and v4.8.4.

Seems it's not a problem belongs to Node version.

**Comment by crookedneighbor** [comment]
I'll look into it tonight.

**Comment by shirohana** [comment]
By the way, could you also upgrade the dependencies? Although there's only dev-dependencies, but It will let contributions easier :)

**Comment by crookedneighbor** [comment]
On my list of things to do :)

**Comment by crookedneighbor** [comment]
Feel free to open a PR that updates them.

**Comment by shirohana** [comment]
I found there's some rule changed in newer releases, maybe it's the main reason.

I can try to upgrade them :)

https://standardjs.com/changelog.html

**Comment by crookedneighbor** [comment]
Closed with https://github.com/crookedneighbor/markdown-it-link-attributes/pull/16

**Pull request closed without merging**
